const rusCityes = [
    'Апрелевка',
    'Балашиха ',
    'Бронницы',
    'Верея',
    'Видное',
    'Волоколамск',
    'Воскресенск',
    'Высоковск',
    'Голицыно',
    'Дзержинский',
    'Дмитров',
    'Долгопрудный',
    'Домодедово',
    'Дрезна',
    'Дубна',
    'Егорьевск',
    'Жуковский',
    'Зарайск',
    'Звенигород',
    'Ивантеевка',
    'Истра',
    'Кашира',
    'Климовск',
    'Клин',
    'Коломна',
    'Королев',
    'Котельники',
    'Красмоармейск',
    'Красногорск',
    'Краснозаводск',
    'Краснознаменск',
    'Кубинка',
    'Куровское',
    'Ликино-Дулево',
    'Лобня',
    'Лосино-Петровский',
    'Луховицы',
    'Лыткарино',
    'Люберцы',
    'Можайск',
    'Мытищи',
    'Наро-Фоминск',
    'Ногинск',
    'Одинцово',
    'Озеры',
    'Орехово-Зуево',
    'Павловский Посад',
    'Пересвет',
    'Подольск',
    'Протвино',
    'Пушкино',
    'Пущино',
    'Раменское',
    'Реутов',
    'Рошаль',
    'Руза',
    'Сергиев Посад',
    'Серпухов',
    'Солнечногорск',
    'Старая Купавна',
    'Ступино',
    'Талдом',
    'Фрязино',
    'Химки',
    'Хотьково',
    'Черноголовка ',
    'Чехов',
    'Шатура',
    'Щелково',
    'Электрогорск',
    'Электросталь',
    'Электроугли',
    'Юбилейный',
    'Яхрома',
    'Москва'
];

const engCityes = [
   'Aprelevka',
   'Balashikha',
   'Bronnitsy',
   'Vereya',
   'Vidnoje',
   'Volokolamsk',
   'Voskresensk',
   'Vysokovsk',
   'Golitsyno',
   'Dzerzhinsky',
   'Dmitrov',
   'Dolgoprudny',
   'Domodedovo',
   'Drezna',
   'Dubna',
   'Egoryevsk',
   'Zhukovsky',
   'Zaraisk',
   'Zvenigorod',
   'Ivanteevka',
   'Istra',
   'Kashira',
   'Klimovsk',
   'Klin',
   'Kolomna',
   'Korolev',
   'Kotelniki',
   'Krasnoarmeisk',
   'Krasnogorsk',
   'Krasnozavodsk',
   'Krasnoznamensk',
   'Kubinka',
   'Kurovskoe',
   'Likino-Dulevo',
   'Lobnya',
   'Losino-Petrovsky',
   'Lukhovitsy',
   'Lytkarino',
   'Lubertsy',
   'Mozhaisk',
   'Mytishchi',
   'Naro-Fominsk',
   'Noginsk',
   'Odintsovo',
   'Ozery',
   'Orekhovo-Zuyevo',
   'Pavlovsky Posad',
   'Peresvet',
   'Podolsk',
   'Protvino',
   'Pushkino',
   'Pushchino',
   'Ramenskoye',
   'Reutov',
   'Roshal',
   'Ruza',
   'Sergiev Posad',
   'Serpukhov',
   'Solnechnogorsk',
   'Staraya Kupavna',
   'Stupino',
   'Taldom',
   'Fryazino',
   'Khimki',
   'Khotkovo',
   'Chernogolovka ',
   'Chekhov',
   'Shatura',
   'Shchelkovo',
   'Elektrogorsk',
   'Electrostal',
   'Electrougli',
   'Yubileiny',
   'Yakhroma',
   'Moscow'
];

export default{ rusCityes, engCityes }

